spring.application.name=INVOICE-SERVICE

# Local development environment
spring.profiles.active=dev
server.port=5671

# Dev file upload directory (relative inside project)
file.upload-dir=uploaded_files
spring.datasource.url=jdbc:postgresql://localhost:5432/Invoice
spring.datasource.username=postgres
spring.datasource.password=Narvee123$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Use valid schema name


