-- Repair primary keys that were created without an identity, which made every
-- INSERT into them fail.
--
-- Cause. invoice.manage_users and invoice.updated_profile are each mapped by TWO
-- services, with different id strategies:
--
--   Invoice-Login   ManageUsers / Admin        @Id @GeneratedValue(IDENTITY)   (writes)
--   Invoice-Service ManageUser  / AdminSettings @Id, no @GeneratedValue, @Immutable (reads)
--
-- Both services run ddl-auto=update, so whichever starts first creates the table.
-- When Invoice-Service wins, Hibernate emits a plain "id bigint not null" with no
-- identity, and ddl-auto=update never retrofits one onto an existing column. The
-- writing service then fails on every insert with
--
--   ERROR: null value in column "id" of relation "manage_users" violates not-null constraint
--
-- surfaced to callers as a misleading 409 "Required field is missing", which is
-- why registration was impossible. Tables with a single owner (otp, roles,
-- user_info) were unaffected and did get proper identity columns.
--
-- The entity mappings have been aligned so newly created tables are correct
-- regardless of start order. This migration repairs databases already built the
-- wrong way. It runs after Hibernate (see FlywayAfterJpaConfig), so the tables
-- exist by the time it executes.
--
-- Idempotent: skips a table that is absent, and skips a column that already has
-- an identity or any other default, so it is a no-op on a correct database.

DO $$
DECLARE
  tbl      text;
  next_id  bigint;
BEGIN
  FOREACH tbl IN ARRAY ARRAY['manage_users', 'updated_profile'] LOOP

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'invoice' AND table_name = tbl
    ) THEN
      CONTINUE;
    END IF;

    -- Already generated (identity, or a serial's nextval default): leave alone.
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'invoice' AND table_name = tbl
          AND column_name  = 'id'
          AND (is_identity = 'YES' OR column_default IS NOT NULL)
    ) THEN
      CONTINUE;
    END IF;

    -- PostgreSQL refuses ADD GENERATED on a nullable column. These are primary
    -- keys so they are already NOT NULL, but a table half-built by an older
    -- Hibernate may not be - make it explicit rather than fail the migration.
    EXECUTE format('ALTER TABLE invoice.%I ALTER COLUMN id SET NOT NULL', tbl);

    -- Start above the highest id already present so the new sequence cannot
    -- collide with rows inserted while the column had no default.
    EXECUTE format('SELECT coalesce(max(id), 0) + 1 FROM invoice.%I', tbl)
      INTO next_id;

    EXECUTE format(
      'ALTER TABLE invoice.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      tbl, next_id);

    -- BY DEFAULT rather than ALWAYS: it matches the other identity columns in
    -- this schema and still permits an explicit id, which data migrations and
    -- restores rely on.

    RAISE NOTICE 'invoice.%.id promoted to identity, starting at %', tbl, next_id;
  END LOOP;
END $$;
